# 线性代数

## 标量

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

## 长度 维度 形状

In [5]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

## 矩阵

In [10]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
# 矩阵转置 
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量

In [16]:
X = torch.arange(24).reshape([2,3,4])
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质

In [17]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存 将 A 的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [18]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [47]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape, len(X)

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]),
 2)

## 降维

In [20]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [21]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [23]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [24]:
A.sum(axis=[0,1])

tensor(190.)

In [26]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

## 非降维求和

In [27]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [28]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [30]:
# 沿某个轴计算元素累积总和(axis=0 按行计算)
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积(Dot Product)

In [31]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [32]:
torch.sum(x * y)

tensor(6.)

## 矩阵-向量积(matrix-vector product)

In [35]:
# torch.mv(A, x) 执行矩阵-向量积
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵-矩阵 乘法(matrix-matrix multiplication)

In [41]:
B = torch.ones(4, 3)
A, B, torch.mm(A, B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

## 范数

In [43]:
# L2 范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [44]:
# L1 范数
torch.abs(u).sum()

tensor(7.)

In [45]:
# 矩阵的 Frobenius 范数 (Frobenius norm) 是矩阵元素平方和的平方根
torch.norm(torch.ones(4, 9))

tensor(6.)

## 范数和目标

在深度学习中，我们经常试图解决优化问题：最大化分配给观测数据的概率，最小化预测和真实观测之间的距离。
用向量表示物品(单词、产品、新闻、文章)，以便最小化相似项目之间的距离，最大化不同项目之间的距离。
目标，或许是深度学习算法最重要的组成部分(除了数据)，通常被表达为范数

## 小结

- 标量、向量、矩阵、张量 是线性代数中的基本数学对象
- 向量泛化自标量，矩阵泛化自向量
- 标量、向量、矩阵、张量 分别具有 0 1 2 和任意数量的轴
- 一个张量可以通过sum和mean 沿指定的轴降低维度
- 两个矩阵的按元素乘法被称为 hadamard 积。它与矩阵乘法不同
- 在深度学习中，我们经常使用范数，如L1范数、L2范数和 Frobenius 范数
- 我们可以对标量、向量、矩阵、张量 执行各种操作

## 练习

1. 证明一个矩阵 $A$ 的转置的转置是 $A$，即 $(A^T)^T=A$。

$$
设 B = A^T, C = B^T
$$
$$
那么根据转置定义, b_{ji} = a_{ij}, c_{ij} = b_{ji}
$$
$$
即 c_{ij} = a_{ij}, 即 C = B^T = (A^T)^T = A, 得 (A^T)^T = A
$$

2. 给出两个矩阵 $A$ 和 $B$ ，证明“它们转置的和”等于“它们和的转置”，即 $A^T + B^T = (A + B)^T$。

$$
设 C = A + B
$$
$$
由 c_{ij} = a_{ij} + b_{ij} 得 c_{ji} = a_{ji} + b_{ji}
$$
$$
即 C^T = A^T + B^T, 又 C = A + B 得 (A + B)^T = A^T + B^T
$$

3. 给定任意方阵 $A$ ， $A + A^T$ 总是对称的吗?为什么?

$$
设 B = A + A^T 则 b_{ij} = a_{ij} + a_{ji}
$$
$$
则 b_{ji} = a_{ji} + a_{ij} = a_{ij} + a_{ji} = b{ij}
$$
$$
即 B 为对称阵, 即 A + A^T 为对称阵
$$

4. 我们在本节中定义了形状 $(2, 3, 4)$ 的张量X。len(X)的输出结果是什么？

In [49]:
X, len(X)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2)

5. 对于任意形状的张量X,len(X)是否总是对应于X特定轴的长度?这个轴是什么?

总对应 axis=0 的轴

6. 运行 A/A.sum(axis=1) ，看看会发生什么。你能分析原因吗？

In [59]:
A, A.sum(axis=1), A.shape, A.sum(axis=1).shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5, 4]),
 torch.Size([5]))

In [58]:
A/A.sum(axis=1) 
# 报错 The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [62]:
# 可以运行 A/A.sum(axis=1, keepdim=True)
# 在 axis != 0 时 一般需要加上 keepdim = True
print(A.sum(axis=1, keepdim=True))
A/A.sum(axis=1, keepdim=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

7. 考虑一个具有形状的张量 $(2, 3, 4)$ ，在轴0、1、2上的求和输出是什么形状?

In [65]:
Z = torch.ones(2, 3, 4)
Z1 = Z.sum(axis=0)
Z2 = Z.sum(axis=1)
Z3 = Z.sum(axis=2)
Z1, Z2, Z3, Z1.size(), Z2.size(), Z3.size()

(tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]),
 torch.Size([3, 4]),
 torch.Size([2, 4]),
 torch.Size([2, 3]))

8. 为 **linalg.norm** 函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?

linalg.norm(A, ord=None, dim=None, keepdim=False, *, out=None, dtype=None) -> Tensor
参数：
- A(Tensor) -形状为 (\*, n) 或 (\*, m, n) 的张量，其中 \* 是零个或多个批次维度
- ord(int,float,inf,-inf,'fro','nuc',可选的) - 规范的顺序。默认：None
- dim(int,元组[int],可选的) - 计算向量或矩阵范数的维度。见上面的行为时dim= None.默认：None
- keepdim(bool,可选的) -如果设置为 True ，则缩小后的尺寸将作为尺寸为 1 的尺寸保留在结果中。默认值：False

关键字参数：
- out(Tensor,可选的) -输出张量。如果 None 则忽略。默认值：None。
- dtype(torch.dtype， 可选的) -如果指定，则在执行操作之前将输入张量强制转换为 dtype，并且返回的张量类型将为 dtype 。默认值：None

ord 定义计算的范数。支持以下规范：
| ord | 矩阵的范数 | 向量的范数 |
| -- | -- | -- |
| None(默认) | Frobenius norm(弗罗贝尼乌斯范数) | 2-norm |
| 'fro' | Frobenius norm | 不支持 |
| 'nuc' | 核范数 | 不支持 |
| inf | max(sum(abs(x), dim=1)) | max(abs(x)) |
| -inf | min(sum(abs(x), dim=1)) | min(abs(x)) |
| 0 | 不支持 | sum(x!=0) |
| 1 | max(sum(abs(x), dim=0)) | 如下 |
| -1 | min(sum(abs(x), dim=0)) | 如下 |
| 2 | 最大奇异值 | 如下 |
| -2 | 最小奇异值 | 如下 |
| 其他 int 或 float | 不支持 | $sum(abs(x)^{ord})^{(1/ord)}$ |

In [94]:
A, B, C = torch.ones(3,4), torch.ones(3,4,5), torch.arange(12, dtype=torch.float32).reshape([2,2,3])
torch.linalg.norm(A), torch.linalg.norm(B), torch.linalg.norm(C), torch.linalg.norm(C, dim=1, ord=torch.inf)

(tensor(3.4641),
 tensor(7.7460),
 tensor(22.4944),
 tensor([[ 3.,  4.,  5.],
         [ 9., 10., 11.]]))